
// src/services/aiService.ts

/**
 * AI Service for Promjum
 * 
 * This file handles all interactions with AI providers (e.g., OpenAI, Gemini).
 * Currently set up as a skeleton for OpenAI integration.
 */

// import OpenAI from 'openai'; // Un-comment when you install the library: npm install openai

// TODO: Replace with your actual API Key usage strategy (Env var recommended)
// const apiKey = import.meta.env.VITE_OPENAI_API_KEY; 

/*
const openai = new OpenAI({
  apiKey: apiKey,
  dangerouslyAllowBrowser: true // Note: For production, call via your own backend to hide the key!
});
*/

export interface StoryParams {
    vocabList: string[];
    topic?: string;
    level?: 'A1' | 'A2' | 'B1' | 'B2';
}

export interface GeneratedStory {
    title: string;
    titleTh: string;
    content: string; // Full text
    sentences: {
        text: string;
        translation: string;
    }[];
}

/**
 * Generates a short story based on vocabulary list.
 * @param params StoryParams
 * @returns Promise<GeneratedStory>
 */
export const generateStory = async (params: StoryParams): Promise<GeneratedStory> => {
    console.log("Generating story with params:", params);

    // 1. Construct the Prompt
    const prompt = `
    Create a short story (5 sentences max) using these English words: ${params.vocabList.join(', ')}.
    Topic: ${params.topic || 'General'}.
    Level: ${params.level || 'A1'}.
    
    Return JSON format:
    {
      "title": "Story Title (English)",
      "titleTh": "Story Title (Thai)",
      "sentences": [
        { "text": "Sentence 1...", "translation": "Translation 1..." }
      ]
    }
  `;

    // 2. Mock Response (Remove this when connecting real API)
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    return {
        title: "The " + (params.topic || "Adventure"),
        titleTh: "การผจญภัย",
        content: "This is a mock story generated by the skeleton service.",
        sentences: [
            { text: `This is a story about ${params.vocabList[0] || 'something'}.`, translation: `นี่คือเรื่องราวเกี่ยวกับ ${params.vocabList[0] || 'บางสิ่ง'}` },
            { text: "It is generated by the placeholder AI service.", translation: "มันถูกสร้างขึ้นโดยบริการ AI จำลอง" },
            { text: "You need to connect OpenAI API key to make it real.", translation: "คุณต้องเชื่อมต่อ OpenAI API key เพื่อให้ใช้งานได้จริง" }
        ]
    };

    /* 
    // 3. Real Implementation Example (Un-comment to use)
    
    try {
      const completion = await openai.chat.completions.create({
        messages: [{ role: "user", content: prompt }],
        model: "gpt-3.5-turbo",
        response_format: { type: "json_object" } // Ensure you ask for JSON in prompt
      });
  
      const result = JSON.parse(completion.choices[0].message.content);
      return result as GeneratedStory;
  
    } catch (error) {
      console.error("AI Generation Failed:", error);
      throw error;
    }
    */
};

export const listAvailableVoices = () => {
    // Helper to list web speech voices if needed
    return window.speechSynthesis.getVoices();
};
